# Generated by Django 3.2.4 on 2021-06-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Categoria', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.ImageField(null=True, upload_to='productos')),
                ('Precio', models.IntegerField()),
            ],
        ),
    ]
