# Generated by Django 3.2.4 on 2021-06-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Categoria',
            field=models.CharField(choices=[('autos', 'AUTOS'), ('celulares', 'CELULARES'), ('electrodomesticos', 'ELECTRODOMESTICOS'), ('muebles', 'MUEBLES')], default='default', max_length=50),
        ),
    ]
