# Generated by Django 3.2.4 on 2021-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0002_alter_productos_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mail', models.EmailField(max_length=254)),
                ('Mensaje', models.TextField()),
            ],
        ),
    ]
