# Generated by Django 3.2.4 on 2021-06-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsuarioIdent', models.CharField(max_length=50)),
                ('Titulo', models.CharField(max_length=50)),
                ('Categoria', models.CharField(choices=[('autos', 'AUTOS'), ('celulares', 'CELULARES'), ('electrodomesticos', 'ELECTRODOMESTICOS'), ('muebles', 'MUEBLES')], default='default', max_length=50)),
                ('Descripcion', models.TextField()),
                ('Imagen', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
            ],
        ),
    ]
