# Generated by Django 3.2.4 on 2021-06-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0004_carritous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritous',
            name='Imagen',
            field=models.CharField(max_length=200),
        ),
    ]
