# Generated by Django 3.2.4 on 2021-06-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0005_alter_carritous_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritous',
            name='Imagen',
        ),
    ]
